apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: demo-clone
  name: demo-clone
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template: #Pod template's structure is the absolute same with Deployment
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.12
          ports:
            - containerPort: 80
  updateStrategy:
    partition: 4
    type: InPlaceIfPossible     # Use In-Place strategy as possible, otherwise use recreate
    maxUnavailable: 5
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 10   # Grace wait time before each pod not ready