apiVersion: apps.kruise.io/v1alpha1
kind: ContainerRecreateRequest
metadata:
  namespace: default
  name: crr-test
spec:
  podName: demo-clone-5qrh9 # should be your pod name
  containers:       # container to be recreated, contains 1 at least
    - name: nginx    # should be your container name
  strategy:
    failurePolicy: Fail
    orderedRecreate: false
    terminationGracePeriodSeconds: 30
    unreadyGracePeriodSeconds: 3
    minStartedSeconds: 10
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 1800